### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by lixuzhang** [fedeinthemix/chez-scmutils#1]
$ make CHEZ=scheme
scheme --program compile-all.ss
compiling ./scmutils/base.sls with output to ./scmutils/base.so
Exception: library (mit core) not found
make: *** [Makefile:37: build] Error 127

**Comment by fedeinthemix** [comment]
A dependency is missing. You need to install chez-mit

https://github.com/fedeinthemix/chez-mit

and make sure chez-scheme can find it.
