### ISSUE TITLE
Publish to akku package manager?

### ISSUE THREAD

**Issue by dakling** [fedeinthemix/chez-scmutils#2]
Hi, 

thanks for your work on this! Have you considered publishing this package (and the dependency chez-mit) to the repository of the cross-implementation package manager [akku](https://gitlab.com/akkuscm/akku)? If you are ok with that, I can try to take of that.

Best regards

**Comment by fedeinthemix** [comment]
Please be aware that the library did undergo only limited testing. That said, if you are willing to do the work, feel free to make it available through akku.

**Comment by weinholt** [comment]
@dakling Hey, you submitted these package to Akku and this is the only way I found to contact you. There are three problems with the packages:

* The license field should not be `NOASSERTION`. I haven't done a thorough check but it looks like `GPL-3.0-or-later` is appropriate.
* chez-scmutils should not use a git dependency on chez-mit. You can either change it by hand to `("chez-mit" "^0.0.0-alpha")` or wait for the chez-mit upload & then do `akku update; akku install chez-mit` which should modify Akku.manifest appropriately.
* Your GPG key is missing from the keyservers, there's a note about this in the manpage. Do: `gpg --keyserver pgp.mit.edu --send-keys 1D4215012B063A400CC11043F323F1344CFA8077`.

**Comment by dakling** [comment]
Thanks, makes sense - I just uploaded my key to the correct keyserver, and have also edited the manifest of chez-scmutils accordingly (haven't uploaded yet, though).

As far as the licenses go, chez-scmutils, as you said, probably inherits the GPL from the original package. However, I was unable to find any license information on chez-mit. @fedeinthemix could you maybe quickly comment on the license of chez-mit (which I assume you wrote)?

**Comment by fedeinthemix** [comment]
The license for `chez-mit` is written in the header of each ".scs" file and is the same as the one for `chez-scmutils`: GPL 3 or later.

**Comment by dakling** [comment]
thanks for the quick reply (and sorry I didn't think of checking the source files themselves) - I just uploaded the improved versions to akku.
